# Generated by Django 4.2.5 on 2023-09-16 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_product_description_alter_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
