# Generated by Django 4.2.5 on 2023-09-18 10:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_product_active_product_winner_alter_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 10, 0, 35, 136975)),
        ),
    ]
