# Generated by Django 4.2.5 on 2023-09-18 10:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_comments_date_alter_product_winner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=datetime.datetime(2023, 9, 18, 10, 36, 48, 219626)),
        ),
    ]
